//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace de.upb.hip.mobile.pcl.BusinessLayer.Models
{
	using Realms;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class AppertizerPage : RealmObject, IIdentifiable
	{
		//Attributes
		[ObjectId]
		private string _id{ get; set; }
		public string Id{
			get{ return _id; }
			set{ Realm.GetInstance ().Write (() => _id = value); }
		}

		private string _text{ get; set; }
		public string Text{
			get{ return _text; }
			set{ Realm.GetInstance ().Write (() => _text = value); }
		}

		//Associations
		public virtual Image Image{ get; set; }

		// Contructor
		public AppertizerPage(){
		}
	}
}

