//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/*Copyright (C) 2016 History in Paderborn App - Universit�t Paderborn
 
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.*/
namespace de.upb.hip.mobile.pcl.BusinessLayer.Models
{
	using Realms;
	using System;
    using System.Collections;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class ExhibitSet : RealmObject, IIdentifiable, IEnumerable<Exhibit>
    {
		//Attributes
		[ObjectId]
		public string Id{ get; set; }

		public virtual IList<StringElement> Categories{ get; }

		public virtual GeoLocation Position{ get; set; }

		//Associations
		public virtual IList<Exhibit> ActiveSet{ get; }

		public virtual IList<Exhibit> InitSet{ get; }

		// Contructor
		public ExhibitSet(){
		}

        public Exhibit this[int index]
        {
            get { return ActiveSet.ElementAt<Exhibit>(index); }
            set { ActiveSet.Insert(index, value); }
        }

        public IEnumerator<Exhibit> GetEnumerator()
        {
            return ActiveSet.GetEnumerator();
            //throw new NotImplementedException();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
            //throw new NotImplementedException();
        }
    }
}

