//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace de.upb.hip.mobile.pcl.BusinessLayer.Models
{
	using Realms;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ExhibitSet : RealmObject, IIdentifiable
	{
		//Attributes
		[ObjectId]
		private string _id{ get; set; }
		public string Id{
			get{ return _id; }
			set{ Realm.GetInstance ().Write (() => _id = value); }
		}

		private RealmList<StringElement> _categories{ get; }
		public IList<StringElement> Categories{
			get{ return _categories; }
		}

		//Associations
		private RealmList<Exhibit> _activeset = new RealmList<Exhibit> ();
		public IList<Exhibit> ActiveSet{
			 get{ return _activeset; }
		}

		private RealmList<Exhibit> _initset = new RealmList<Exhibit> ();
		public IList<Exhibit> InitSet{
			 get{ return _initset; }
		}

		// Contructor
		protected ExhibitSet(){
		}
	}
}

