//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace de.upb.hip.mobile.pcl.BusinessLayer.Models
{
	using Realms;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GeoPoint : RealmObject, IIdentifiable
	{
		//Attributes
		[ObjectId]
		private string _id{ get; set; }
		public string Id{
			get{ return _id; }
			set{ Realm.GetInstance ().Write (() => _id = value); }
		}

		private double _latitude{ get; set; }
		public double Latitude{
			get{ return _latitude; }
			set{ Realm.GetInstance ().Write (() => _latitude = value); }
		}

		private double _longitude{ get; set; }
		public double Longitude{
			get{ return _longitude; }
			set{ Realm.GetInstance ().Write (() => _longitude = value); }
		}

		//Associations
		// Contructor
		protected GeoPoint(){
		}
	}
}

