//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace de.upb.hip.mobile.pcl.BusinessLayer.Models
{
	using Realms;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Page : RealmObject, IIdentifiable
	{
		//Attributes
		[ObjectId]
		private string _id{ get; set; }
		public string Id{
			get{ return _id; }
			set{ Realm.GetInstance ().Write (() => _id = value); }
		}

		//Associations
		public virtual AppertizerPage AppertizerPage{ get; set; }

		public virtual ImagePage ImagePage{ get; set; }

		public virtual TextPage TextPage{ get; set; }

		public virtual TimeSliderPage TimeSliderPage{ get; set; }

		// Contructor
		protected Page(){
		}
	}
}

