//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/*Copyright (C) 2016 History in Paderborn App - Universit�t Paderborn
 
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.*/
namespace de.upb.hip.mobile.pcl.BusinessLayer.Models
{
	using Realms;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Rectangle : RealmObject, IIdentifiable
	{
		//Attributes
		[ObjectId]
		private string _id{ get; set; }
		public string Id{
			get{ return _id; }
			set{ Realm.GetInstance ().Write (() => _id = value); }
		}

		private int _top{ get; set; }
		public int Top{
			get{ return _top; }
			set{ Realm.GetInstance ().Write (() => _top = value); }
		}

		private int _bottom{ get; set; }
		public int Bottom{
			get{ return _bottom; }
			set{ Realm.GetInstance ().Write (() => _bottom = value); }
		}

		private int _left{ get; set; }
		public int Left{
			get{ return _left; }
			set{ Realm.GetInstance ().Write (() => _left = value); }
		}

		private int _right{ get; set; }
		public int Right{
			get{ return _right; }
			set{ Realm.GetInstance ().Write (() => _right = value); }
		}

		//Associations
		// Contructor
		public Rectangle(){
		}
	}
}

