//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace de.upb.hip.mobile.pcl.BusinessLayer.Models
{
	using Realms;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Rectangle : RealmObject, IIdentifiable
	{
		//Attributes
		[ObjectId]
		private string _id{ get; set; }
		public string Id{
			get{ return _id; }
			set{ Realm.GetInstance ().Write (() => _id = value); }
		}

		private int _topleft{ get; set; }
		public int TopLeft{
			get{ return _topleft; }
			set{ Realm.GetInstance ().Write (() => _topleft = value); }
		}

		private int _topright{ get; set; }
		public int TopRight{
			get{ return _topright; }
			set{ Realm.GetInstance ().Write (() => _topright = value); }
		}

		private int _bottomleft{ get; set; }
		public int BottomLeft{
			get{ return _bottomleft; }
			set{ Realm.GetInstance ().Write (() => _bottomleft = value); }
		}

		private int _bottomright{ get; set; }
		public int BottomRight{
			get{ return _bottomright; }
			set{ Realm.GetInstance ().Write (() => _bottomright = value); }
		}

		//Associations
		// Contructor
		public Rectangle(){
		}
	}
}

