//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace de.upb.hip.mobile.pcl.BusinessLayer.Models
{
	using Realms;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Route : RealmObject, IIdentifiable
	{
		//Attributes
		[ObjectId]
		private string _id{ get; set; }
		public string Id{
			get{ return _id; }
			set{ Realm.GetInstance ().Write (() => _id = value); }
		}

		private string _title{ get; set; }
		public string Title{
			get{ return _title; }
			set{ Realm.GetInstance ().Write (() => _title = value); }
		}

		private string _description{ get; set; }
		public string Description{
			get{ return _description; }
			set{ Realm.GetInstance ().Write (() => _description = value); }
		}

		private int _duration{ get; set; }
		public int Duration{
			get{ return _duration; }
			set{ Realm.GetInstance ().Write (() => _duration = value); }
		}

		private int _distance{ get; set; }
		public int Distance{
			get{ return _distance; }
			set{ Realm.GetInstance ().Write (() => _distance = value); }
		}

		//Associations
		private RealmList<RouteTag> _routetags = new RealmList<RouteTag> ();
		public IList<RouteTag> RouteTags{
			 get{ return _routetags; }
		}

		public virtual Image Image{ get; set; }

		// Contructor
		protected Route(){
		}
	}
}

