//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
/*Copyright (C) 2016 History in Paderborn App - Universit�t Paderborn
 
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
 
       http://www.apache.org/licenses/LICENSE-2.0
 
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.*/
namespace de.upb.hip.mobile.pcl.BusinessLayer.Models
{
	using Realms;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class RouteTag : RealmObject, IIdentifiable
	{
		//Attributes
		[ObjectId]
		private string _id{ get; set; }
		public string Id{
			get{ return _id; }
			set{ Realm.GetInstance ().Write (() => _id = value); }
		}

		private string _tag{ get; set; }
		public string Tag{
			get{ return _tag; }
			set{ Realm.GetInstance ().Write (() => _tag = value); }
		}

		private string _name{ get; set; }
		public string Name{
			get{ return _name; }
			set{ Realm.GetInstance ().Write (() => _name = value); }
		}

		//Associations
		private Image _image{ get; set; }
		public Image Image{
			get{ return _image; }
			set{ Realm.GetInstance ().Write (() => _image = value); }
		}

		// Contructor
		public RouteTag(){
		}
	}
}

