//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace de.upb.hip.mobile.pcl.BusinessLayer.Models
{
	using Realms;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class SliderImage : RealmObject, IIdentifiable
	{
		//Attributes
		[ObjectId]
		private string _id{ get; set; }
		public string Id{
			get{ return _id; }
			set{ Realm.GetInstance ().Write (() => _id = value); }
		}

		private string _imagename{ get; set; }
		public string ImageName{
			get{ return _imagename; }
			set{ Realm.GetInstance ().Write (() => _imagename = value); }
		}

		private int _year{ get; set; }
		public int Year{
			get{ return _year; }
			set{ Realm.GetInstance ().Write (() => _year = value); }
		}

		//Associations
		// Contructor
		protected SliderImage(){
		}
	}
}

