//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace de.upb.hip.mobile.pcl.BusinessLayer.Models
{
	using Realms;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class TimeSliderPage : RealmObject, IIdentifiable
	{
		//Attributes
		[ObjectId]
		private string _id{ get; set; }
		public string Id{
			get{ return _id; }
			set{ Realm.GetInstance ().Write (() => _id = value); }
		}

		private string _title{ get; set; }
		public string Title{
			get{ return _title; }
			set{ Realm.GetInstance ().Write (() => _title = value); }
		}

		private string _text{ get; set; }
		public string Text{
			get{ return _text; }
			set{ Realm.GetInstance ().Write (() => _text = value); }
		}

		private RealmList<LongElement> _dates{ get; }
		public IList<LongElement> Dates{
			get{ return _dates; }
		}

		//Associations
		public virtual Audio Audio{ get; set; }

		private RealmList<Image> _images;
		public IList<Image> Images{
			 get{ return _images; }
		}

		// Contructor
		public TimeSliderPage(){
		}
	}
}

