#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("de.upb.hip.mobile.droid.Resource", IsApplication=true)]

namespace de.upb.hip.mobile.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int nav_drawer_entries = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int textColorPrimary = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int textColorPrimaryInverse = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int textColorSecondary = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int textColorSecondaryInverse = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int textOverlayForImage = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050004
			public const int activity_horizontal_margin = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int activity_vertical_margin = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int button_elevation = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int button_press_elevation = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int fab_size = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int trackingmode_button_size = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hiphop = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int semitransparent_gray = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0004
			public const int myButton = 2131361796;
			
			// aapt resource value: 0x7f0a0000
			public const int splashScreenActionText = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int splashScreenProgressBar = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int splashScreenRetryButton = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int splashScreenWaitingText = 2131361793;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_splash_screen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f070000
			public const int route_activity_duration_minutes = 2131165184;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f06002a
			public const int cancel = 2131099690;
			
			// aapt resource value: 0x7f060025
			public const int creating_map = 2131099685;
			
			// aapt resource value: 0x7f06001a
			public const int departure = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int destination = 2131099676;
			
			// aapt resource value: 0x7f060024
			public const int download_road = 2131099684;
			
			// aapt resource value: 0x7f060019
			public const int drawer_close = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int drawer_open = 2131099672;
			
			// aapt resource value: 0x7f060022
			public const int empty_route = 2131099682;
			
			// aapt resource value: 0x7f06002b
			public const int gps_not_enabled_message = 2131099691;
			
			// aapt resource value: 0x7f060028
			public const int gps_settings = 2131099688;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			// aapt resource value: 0x7f06001f
			public const int itinerary_markers_title = 2131099679;
			
			// aapt resource value: 0x7f060036
			public const int licensing_couchbase_body_text = 2131099702;
			
			// aapt resource value: 0x7f060035
			public const int licensing_couchbase_title_text = 2131099701;
			
			// aapt resource value: 0x7f060030
			public const int licensing_google_material_body_text = 2131099696;
			
			// aapt resource value: 0x7f06002f
			public const int licensing_google_material_title_text = 2131099695;
			
			// aapt resource value: 0x7f060034
			public const int licensing_osmbonuspack_body_text = 2131099700;
			
			// aapt resource value: 0x7f060033
			public const int licensing_osmbonuspack_title_text = 2131099699;
			
			// aapt resource value: 0x7f060032
			public const int licensing_osmdroid_body_text = 2131099698;
			
			// aapt resource value: 0x7f060031
			public const int licensing_osmdroid_title_text = 2131099697;
			
			// aapt resource value: 0x7f06002e
			public const int licensing_title = 2131099694;
			
			// aapt resource value: 0x7f060027
			public const int map_quest_key = 2131099687;
			
			// aapt resource value: 0x7f060007
			public const int menu_activity_route_filter = 2131099655;
			
			// aapt resource value: 0x7f06002c
			public const int network_connection = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int network_message = 2131099693;
			
			// aapt resource value: 0x7f060021
			public const int no_route = 2131099681;
			
			// aapt resource value: 0x7f060026
			public const int osm_contributors = 2131099686;
			
			// aapt resource value: 0x7f060020
			public const int route = 2131099680;
			
			// aapt resource value: 0x7f060010
			public const int route_activity_description = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int route_activity_details_start = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int route_activity_distance = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int route_activity_distance_kilometer = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int route_activity_duration = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int route_activity_title = 2131099665;
			
			// aapt resource value: 0x7f06000a
			public const int route_tag_close_with_save_label = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int route_tag_close_without_save_label = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int route_tag_label = 2131099656;
			
			// aapt resource value: 0x7f060029
			public const int settings = 2131099689;
			
			// aapt resource value: 0x7f060017
			public const int splash_screen_check_connection = 2131099671;
			
			// aapt resource value: 0x7f060012
			public const int splash_screen_loading = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int splash_screen_no_connection = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int splash_screen_no_connection_error_message = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int splash_screen_retry = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int splash_screen_waiting = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int start_point = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int step = 2131099678;
			
			// aapt resource value: 0x7f060023
			public const int technical_issue = 2131099683;
			
			// aapt resource value: 0x7f060004
			public const int title_activity_display_image_slider = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int title_activity_display_single_image = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int title_activity_main = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int title_activity_route = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int title_activity_route_details = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int title_activity_route_filter = 2131099654;
			
			// aapt resource value: 0x7f06001b
			public const int via_point = 2131099675;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int AppTheme = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int AppTheme_Base = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int AppTheme_WithActionBar = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int Theme_Transparent = 2131296259;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
