#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("de.upb.hip.mobile.droid.Resource", IsApplication=true)]

namespace de.upb.hip.mobile.droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090000
			public const int nav_drawer_entries = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int colorAccent = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int colorPrimary = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int colorPrimaryDark = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int my_purple = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int textColorPrimary = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int textColorPrimaryInverse = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int textColorSecondary = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int textColorSecondaryInverse = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int textOverlayForImage = 2131099655;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040005
			public const int activity_horizontal_margin = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int activity_vertical_margin = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int button_elevation = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int button_press_elevation = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int fab_size = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int trackingmode_button_size = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hiphop = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int semitransparent_gray = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int mainActivityDrawerLayout = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int mainSwipeContainer = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int mapview = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int splashScreenActionText = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int splashScreenProgressBar = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int splashScreenRetryButton = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int splashScreenWaitingText = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_splash_screen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f080000
			public const int route_activity_duration_minutes = 2131230720;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f07002a
			public const int cancel = 2131165226;
			
			// aapt resource value: 0x7f070025
			public const int creating_map = 2131165221;
			
			// aapt resource value: 0x7f07001a
			public const int departure = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int destination = 2131165212;
			
			// aapt resource value: 0x7f070024
			public const int download_road = 2131165220;
			
			// aapt resource value: 0x7f070019
			public const int drawer_close = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int drawer_open = 2131165208;
			
			// aapt resource value: 0x7f070022
			public const int empty_route = 2131165218;
			
			// aapt resource value: 0x7f07002b
			public const int gps_not_enabled_message = 2131165227;
			
			// aapt resource value: 0x7f070028
			public const int gps_settings = 2131165224;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			// aapt resource value: 0x7f07001f
			public const int itinerary_markers_title = 2131165215;
			
			// aapt resource value: 0x7f070036
			public const int licensing_couchbase_body_text = 2131165238;
			
			// aapt resource value: 0x7f070035
			public const int licensing_couchbase_title_text = 2131165237;
			
			// aapt resource value: 0x7f070030
			public const int licensing_google_material_body_text = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int licensing_google_material_title_text = 2131165231;
			
			// aapt resource value: 0x7f070034
			public const int licensing_osmbonuspack_body_text = 2131165236;
			
			// aapt resource value: 0x7f070033
			public const int licensing_osmbonuspack_title_text = 2131165235;
			
			// aapt resource value: 0x7f070032
			public const int licensing_osmdroid_body_text = 2131165234;
			
			// aapt resource value: 0x7f070031
			public const int licensing_osmdroid_title_text = 2131165233;
			
			// aapt resource value: 0x7f07002e
			public const int licensing_title = 2131165230;
			
			// aapt resource value: 0x7f070027
			public const int map_quest_key = 2131165223;
			
			// aapt resource value: 0x7f070007
			public const int menu_activity_route_filter = 2131165191;
			
			// aapt resource value: 0x7f07002c
			public const int network_connection = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int network_message = 2131165229;
			
			// aapt resource value: 0x7f070021
			public const int no_route = 2131165217;
			
			// aapt resource value: 0x7f070026
			public const int osm_contributors = 2131165222;
			
			// aapt resource value: 0x7f070020
			public const int route = 2131165216;
			
			// aapt resource value: 0x7f070010
			public const int route_activity_description = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int route_activity_details_start = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int route_activity_distance = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int route_activity_distance_kilometer = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int route_activity_duration = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int route_activity_title = 2131165201;
			
			// aapt resource value: 0x7f07000a
			public const int route_tag_close_with_save_label = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int route_tag_close_without_save_label = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int route_tag_label = 2131165192;
			
			// aapt resource value: 0x7f070029
			public const int settings = 2131165225;
			
			// aapt resource value: 0x7f070017
			public const int splash_screen_check_connection = 2131165207;
			
			// aapt resource value: 0x7f070012
			public const int splash_screen_loading = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int splash_screen_no_connection = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int splash_screen_no_connection_error_message = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int splash_screen_retry = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int splash_screen_waiting = 2131165203;
			
			// aapt resource value: 0x7f07001d
			public const int start_point = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int step = 2131165214;
			
			// aapt resource value: 0x7f070023
			public const int technical_issue = 2131165219;
			
			// aapt resource value: 0x7f070004
			public const int title_activity_display_image_slider = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int title_activity_display_single_image = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int title_activity_main = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int title_activity_route = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int title_activity_route_details = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int title_activity_route_filter = 2131165190;
			
			// aapt resource value: 0x7f07001b
			public const int via_point = 2131165211;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int AppTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int AppTheme_Base = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int AppTheme_WithActionBar = 2131361793;
			
			// aapt resource value: 0x7f0a0003
			public const int Theme_Transparent = 2131361795;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
