//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HipMobileUI.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HipMobileUI.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untertitel.
        /// </summary>
        public static string AudioToolbarView_Caption {
            get {
                return ResourceManager.GetString("AudioToolbarView_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string AudioToolbarView_Pause {
            get {
                return ResourceManager.GetString("AudioToolbarView_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string AudioToolbarView_Play {
            get {
                return ResourceManager.GetString("AudioToolbarView_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortschritt.
        /// </summary>
        public static string AudioToolbarView_Progress {
            get {
                return ResourceManager.GetString("AudioToolbarView_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quellen.
        /// </summary>
        public static string AudioTranscriptView_Sources_Title {
            get {
                return ResourceManager.GetString("AudioTranscriptView_Sources_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untertitel.
        /// </summary>
        public static string AudioTranscriptView_Subtitles_Title {
            get {
                return ResourceManager.GetString("AudioTranscriptView_Subtitles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich möchte die Funktion nutzen.
        /// </summary>
        public static string ExhibitDetailsPage_AgreeFeature {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_AgreeFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio startet automatisch sobald eine neue Seite geöffnet wird. Diese Eigenschaft kann unter Menu &gt;&gt; Einstellungen geändert werden..
        /// </summary>
        public static string ExhibitDetailsPage_AudioPlay {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_AudioPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Player.
        /// </summary>
        public static string ExhibitDetailsPage_AudioToolbar {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_AudioToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich möchte die Funktion nicht nutzen.
        /// </summary>
        public static string ExhibitDetailsPage_DisagreeFeature {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_DisagreeFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinweis.
        /// </summary>
        public static string ExhibitDetailsPage_Hinweis {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_Hinweis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Seiten werden automatisch gewechselt, wenn die Audiodatei abgespielt wurde. Diese Eigenschaft kann unter Menu &gt;&gt; Einstellungen geändert werden..
        /// </summary>
        public static string ExhibitDetailsPage_PageSwitch {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_PageSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string ExhibitNearby_Confirm {
            get {
                return ResourceManager.GetString("ExhibitNearby_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sehenwürdigkeit in der Nähe.
        /// </summary>
        public static string ExhibitNearby_ExhibitNearby {
            get {
                return ResourceManager.GetString("ExhibitNearby_ExhibitNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten sie sich.
        /// </summary>
        public static string ExhibitNearby_Question_Part1 {
            get {
                return ResourceManager.GetString("ExhibitNearby_Question_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genauer ansehen?.
        /// </summary>
        public static string ExhibitNearby_Question_Part2 {
            get {
                return ResourceManager.GetString("ExhibitNearby_Question_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string ExhibitNearby_Reject {
            get {
                return ResourceManager.GetString("ExhibitNearby_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Nutzung der App basiert auf Freiwilligkeit. Sämtliche Daten, die im Rahmen der Nutzung der Dienste und Applikation Verwendung finden, dürfen nur erhoben und verarbeitet werden, soweit dies für den Dienst und statistische Forschungs- und Evaluationszwecke erforderlich ist und den Regelungen der Universität Paderborn und dem Datenschutzgesetz NRW entspricht..
        /// </summary>
        public static string LicenseScreenView_Agreement_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Agreement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtsgrundlagen und Einwilligung.
        /// </summary>
        public static string LicenseScreenView_Agreement_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Agreement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beiträge.
        /// </summary>
        public static string LicenseScreenView_Contribution_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Contribution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Software Historisches Paderborn unterliegt dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung bedürfen der schriftlichen Zustimmung der Universität Paderborn. Die Nutzung der Software ist nur für den privaten, nicht kommerziellen Gebrauch gestattet..
        /// </summary>
        public static string LicenseScreenView_Copyright_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Copyright_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string LicenseScreenView_Copyright_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Copyright_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilder erstellt von &lt;a href=&quot;http://www.flaticon.com/authors/madebyoliver/&quot;&gt;Madebyoliver&lt;/a&gt; from &lt;a href=&quot;http://www.flaticon.com/&quot;&gt;www.flaticon.com&lt;/a&gt;..
        /// </summary>
        public static string LicenseScreenView_CreditsImagesAutocarousel_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_CreditsImagesAutocarousel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits der Bilder im Autokarussell.
        /// </summary>
        public static string LicenseScreenView_CreditsImagesAutocarousel_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_CreditsImagesAutocarousel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;http://commonservicelocator.codeplex.com&quot;&gt;Microsoft&lt;/a&gt;, lizensiert unter &lt;a href=&quot;http://commonservicelocator.codeplex.com/license&quot;&gt;Ms-PL&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_CSL_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_CSL_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Service Locator.
        /// </summary>
        public static string LicenseScreenView_CSL_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_CSL_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Daten die die App darstellt werden auf dem Smartphone in einer separaten Datenbank gespeichert. Die App liest und schreibt ausschließlich in dieser Datenbank. Der gesamte Datenverkehr erfolgt lokal..
        /// </summary>
        public static string LicenseScreenView_DatabaseData_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_DatabaseData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbank-Daten.
        /// </summary>
        public static string LicenseScreenView_DatabaseData_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_DatabaseData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für den technischen Betrieb, das Aufspüren von Fehlern steht es dem Nutzer frei Feedback an die Entwickler zu senden. Die Daten enthalten Informationen über Namen und E-Mail-Adresse, die vom User frei gewählt werden können. Die Erhebung und Nutzung dieser Feedback-Daten dienen lediglich der Fehlerbeseitigung und werden zudem in anonymisierter Form für statistischen Forschungs- und Evaluationszwecke ausgewertet. Die Log-Daten werden auf den Servern der Feedback Anwendung Hockeyapp gespeichert..
        /// </summary>
        public static string LicenseScreenView_FeedbackData_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_FeedbackData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback-Daten.
        /// </summary>
        public static string LicenseScreenView_FeedbackData_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_FeedbackData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://github.com/Fody/Fody&quot;&gt;Simon Cropp&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://opensource.org/licenses/mit-license.php&quot;&gt;MIT&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_Fody_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Fody_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fody.
        /// </summary>
        public static string LicenseScreenView_Fody_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Fody_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Fragen bestehen, die diese Datenschutzerklärung nicht beantwortet, oder wenn zu einzelnen Punkten vertiefte Informationen gewünscht werden, gibt der Software Innovation Campus Paderborn gerne weitere Auskunft. E-Mail: hip-app@campus.uni-paderborn.de Telefon +49 5251 603358 Postalisch: Universität Paderborn Software Innovation Campus Warburger Str. 100 D-33098 Paderborn.
        /// </summary>
        public static string LicenseScreenView_FurtherInfo_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_FurtherInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitergehende Informationen.
        /// </summary>
        public static string LicenseScreenView_FurtherInfo_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_FurtherInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://github.com/bitstadium/HockeySDK-Android&quot;&gt;Microsoft&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://raw.githubusercontent.com/bitstadium/HockeySDK-Xamarin/master/LICENSE.md&quot;&gt;Lizenz&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_HockeyApp_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_HockeyApp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HockeyApp.
        /// </summary>
        public static string LicenseScreenView_HockeyApp_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_HockeyApp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HiP (History in Paderborn) ist eine Plattform der:
        ///&lt;a href=&quot;http://www.uni-paderborn.de&quot;&gt;Universität Paderborn&lt;/a&gt;
        ///Warburger Str. 100 
        ///33098 Paderborn 
        ///Tel.: +49 5251 60-0 
        ///
        ///Die Universität Paderborn ist eine vom Land NRW getragene, rechtsfähige Körperschaft des Öffentlichen Rechts. Sie wird durch den Präsidenten vertreten.
        ///
        ///Umsatzsteuer-Identifikationsnummer gemäß § 27 a Umsatzsteuergesetz: DE 811209907
        ///
        ///Zuständige Aufsichtsbehörde: Ministerium für Innovation, Wissenschaft, Forschung und Technolo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseScreenView_Impressum_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Impressum_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        public static string LicenseScreenView_Impressum_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Impressum_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://github.com/Itinero&quot;&gt;Ben Abelshausen&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://opensource.org/licenses/Apache-2.0&quot;&gt;Apache License 2.0&lt;/a&gt; durch Erlaubnis. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_Itinero_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Itinero_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itinero.
        /// </summary>
        public static string LicenseScreenView_Itinero_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Itinero_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Universität Paderborn übernimmt keine Garantie dafür, dass der Dienst fehlerfrei und jederzeit ohne Unterbrechung zur Verfügung steht. Eventuelle Datenverluste infolge technischer Störungen sowie die Kenntnisnahme vertraulicher Daten durch unberechtigte Zugriffe Dritter können nicht in jedem Fall ausgeschlossen werden. Die Universität Paderborn übernimmt keine Verantwortung für die Korrektheit der durch den Dienst zur Verfügung gestellten Informationen. Sie haftet auch nicht für den Inhalt, insbesondere [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseScreenView_Liability_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Liability_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftung.
        /// </summary>
        public static string LicenseScreenView_Liability_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Liability_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lizenzen.
        /// </summary>
        public static string LicenseScreenView_License_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_License_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://mapicons.mapsmarker.com/&quot;&gt;Maps Icons Collection&lt;/a&gt;, lizensiert unter &lt;a href=&quot;http://creativecommons.org/licenses/by-sa/3.0/&quot;&gt;CC-BY-SA 3.0&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_MapIcons_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_MapIcons_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Icons.
        /// </summary>
        public static string LicenseScreenView_MapIcons_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_MapIcons_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://design.google.com/icons/&quot;&gt;Google&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://opensource.org/licenses/Apache-2.0&quot;&gt;Apache License 2.0&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_MaterialIcons_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_MaterialIcons_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Icons.
        /// </summary>
        public static string LicenseScreenView_MaterialIcons_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_MaterialIcons_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://github.com/MKergall/osmbonuspack&quot;&gt;MKergall&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://raw.githubusercontent.com/MKergall/osmbonuspack/master/LICENSE.md&quot;&gt;GNU Lesser General Public License 3.0 (LGPL 3.0)&lt;/a&gt; (ohne §5.d und §5.e). Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_OSMBonusPack_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_OSMBonusPack_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSMBonusPack.
        /// </summary>
        public static string LicenseScreenView_OSMBonusPack_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_OSMBonusPack_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://github.com/osmdroid/osmdroid&quot;&gt;osmdroid&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://raw.githubusercontent.com/osmdroid/osmdroid/master/LICENSE&quot;&gt;Apache License 2.0&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_Osmdroid_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Osmdroid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osmdroid.
        /// </summary>
        public static string LicenseScreenView_Osmdroid_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Osmdroid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://osmsharp.com/&quot;&gt;Ben Abelshausen&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://opensource.org/licenses/mit-license.php&quot;&gt;MIT&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_OsmSharp_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_OsmSharp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OsmSharp.
        /// </summary>
        public static string LicenseScreenView_OsmSharp_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_OsmSharp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historisches in Paderborn ist ein nicht-kommerzieller interaktiver Stadtführer der Universität Paderborn für mobile Endgeräte, dessen Nutzung auf Freiwilligkeit basiert. Die bei der Nutzung erhobenen Daten werden nur für die hier beschriebenen Zwecke verwendet und an keine Dritte weitergegeben. Diese Datenschutzerklärung beschreibt den Umgang mit personenbezogenen Daten innerhalb der Stadtführer App. Mit der Installation der App erklärt sich der Nutzer mit dieser Datenschutzerklärung einverstanden und kann  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseScreenView_PrivacyPolicy_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_PrivacyPolicy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutzerklärung.
        /// </summary>
        public static string LicenseScreenView_PrivacyPolicy_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_PrivacyPolicy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://github.com/realm/realm-java&quot;&gt;Realm&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://raw.githubusercontent.com/realm/realm-java/master/LICENSE&quot;&gt;Apache License 2.0&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_Realm_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Realm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm for Android.
        /// </summary>
        public static string LicenseScreenView_Realm_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Realm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://github.com/itinero/reminiscence/&quot;&gt;Ben Abelshausen&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://opensource.org/licenses/mit-license.php&quot;&gt;MIT&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_Reminiscence_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Reminiscence_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminiscence.
        /// </summary>
        public static string LicenseScreenView_Reminiscence_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Reminiscence_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Datenschutzerklärung hat einen rein informativen Charakter, beschreibt aber verlässlich den aktuellen Stand des Systems. Änderungen innerhalb des Systems, die die Nutzung personenbezogener Daten betreffen, werden umgehend in die Datenschutzerklärung eingepflegt, um den Nutzerinnen und Nutzern jederzeit den aktuellen datenschutzrechtlichen Stand des Systems darlegen zu können. Die jeweiligen Sachverhalte ergeben sich aus den einschlägigen rechtlichen Regelungen und sind unabhängig von dieser Erläuterun [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseScreenView_RightOfPP_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_RightOfPP_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtlicher Status der Datenschutzerklärung.
        /// </summary>
        public static string LicenseScreenView_RightOfPP_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_RightOfPP_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://github.com/jamesmontemagno/SettingsPlugin&quot;&gt;James Montemagno&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://github.com/jamesmontemagno/SettingsPlugin/blob/master/LICENSE&quot;&gt;MIT&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_SettingsPlugin_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_SettingsPlugin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Plugin.
        /// </summary>
        public static string LicenseScreenView_SettingsPlugin_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_SettingsPlugin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Applikation Historisches Paderborn ist eine experimentelle Software, welche zu Studien- und Forschungszwecken an der Universität Paderborn erstellt wurde. Die Software stellt historische Informationen als auch Kartendaten dar, wobei weder die Vollständigkeit noch die Korrektheit der Daten garantiert wird. Die Smartphone Applikation führt eine Positionsschätzung mit Hilfe von GPS durch. Die Genauigkeit der Positionsschätzung ist abhängig von vielen Faktoren, deshalb kann eine fehlerfreie Funktion nicht g [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseScreenView_ToU_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_ToU_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzungsbedingungen.
        /// </summary>
        public static string LicenseScreenView_ToU_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_ToU_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Rahmen der Feedback Funktion die jeder Nutzer freiwillig nutzen kann, muss dieser einen Namen und eine Emailadresse angeben um eine Nachricht an die Entwickler zu senden. Diese Daten werden verschlüsselt versendet. Es werden ebenfalls keinerlei Daten aus dem privaten Speicher des Smartphones gelesen die nicht Teil der Datenbank sind..
        /// </summary>
        public static string LicenseScreenView_Transparancy_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Transparancy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichtbarkeit der Daten / Transparenz.
        /// </summary>
        public static string LicenseScreenView_Transparancy_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Transparancy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://github.com/unitycontainer/unity&quot;&gt;Microsoft&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://opensource.org/licenses/Apache-2.0&quot;&gt;Apache License 2.0&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_Unity_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Unity_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity.
        /// </summary>
        public static string LicenseScreenView_Unity_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Unity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Historisches in Paderborn App ist eine offene Applikation, welche mit einen Google Konto über den Google Playstore sowie dem Apple iTunes App Store heruntergeladen werden kann. In der aktuellen Version bezieht die App seine Daten von einer lokalen Datenbank die bei der Installation der App auf dem Speicher des Smartphones abgelegt wird. Das Kartenmaterial wird je nach Verwendung und Position des Nutzers vom OpenStreetMap Server geladen. Darüber hinaus steht es dem Nutzer frei ein Feedback an die Entwick [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseScreenView_UsagePersonalData_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_UsagePersonalData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erhebung, Verarbeitung und Nutzung personenbezogener Daten.
        /// </summary>
        public static string LicenseScreenView_UsagePersonalData_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_UsagePersonalData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von &lt;a href=&quot;https://github.com/xamarin/AndroidSupportComponents&quot;&gt;Xamarin&lt;/a&gt;, lizensiert unter &lt;a href=&quot;https://github.com/xamarin/AndroidSupportComponents/blob/master/LICENSE.md&quot;&gt;MIT&lt;/a&gt;. Es wurden keine Änderungen vorgenommen..
        /// </summary>
        public static string LicenseScreenView_XSL_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_XSL_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin Support Libraries.
        /// </summary>
        public static string LicenseScreenView_XSL_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_XSL_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einen Moment bitte....
        /// </summary>
        public static string LoadingPage_Subtext {
            get {
                return ResourceManager.GetString("LoadingPage_Subtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historisches Paderborn wird geladen.
        /// </summary>
        public static string LoadingPage_Text {
            get {
                return ResourceManager.GetString("LoadingPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historisches Paderborn.
        /// </summary>
        public static string MainPage_MenuTitle {
            get {
                return ResourceManager.GetString("MainPage_MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string MainPageViewModel_Feedback {
            get {
                return ResourceManager.GetString("MainPageViewModel_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtliche Hinweise.
        /// </summary>
        public static string MainPageViewModel_LegalNotices {
            get {
                return ResourceManager.GetString("MainPageViewModel_LegalNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersicht.
        /// </summary>
        public static string MainPageViewModel_OverviewPage {
            get {
                return ResourceManager.GetString("MainPageViewModel_OverviewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routen.
        /// </summary>
        public static string MainPageViewModel_Routes {
            get {
                return ResourceManager.GetString("MainPageViewModel_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string MainPageViewModel_Settings {
            get {
                return ResourceManager.GetString("MainPageViewModel_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind nicht in Paderborn oder es ist momentan kein GPS Signal vorhanden.
        /// </summary>
        public static string MapRenderer_NoLocation_Text {
            get {
                return ResourceManager.GetString("MapRenderer_NoLocation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlesen pausieren.
        /// </summary>
        public static string RouteDetailsPage_PauseAudio {
            get {
                return ResourceManager.GetString("RouteDetailsPage_PauseAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlesen.
        /// </summary>
        public static string RouteDetailsPage_PlayAudio {
            get {
                return ResourceManager.GetString("RouteDetailsPage_PlayAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route starten.
        /// </summary>
        public static string RouteDetailsPage_StartRoute {
            get {
                return ResourceManager.GetString("RouteDetailsPage_StartRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf der Route.
        /// </summary>
        public static string RouteDetailsPage_Tags {
            get {
                return ResourceManager.GetString("RouteDetailsPage_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string RouteDetailspageViewModel_Back {
            get {
                return ResourceManager.GetString("RouteDetailspageViewModel_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route fortführen.
        /// </summary>
        public static string RouteDetailspageViewModel_ContinueRoute {
            get {
                return ResourceManager.GetString("RouteDetailspageViewModel_ContinueRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string RouteDetailsPageViewModel_Description {
            get {
                return ResourceManager.GetString("RouteDetailsPageViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} km.
        /// </summary>
        public static string RouteDetailsPageViewModel_Distance {
            get {
                return ResourceManager.GetString("RouteDetailsPageViewModel_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min.
        /// </summary>
        public static string RouteDetailsPageViewModel_Duration {
            get {
                return ResourceManager.GetString("RouteDetailsPageViewModel_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte.
        /// </summary>
        public static string RouteDetailsPageViewModel_Map {
            get {
                return ResourceManager.GetString("RouteDetailsPageViewModel_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route neu starten.
        /// </summary>
        public static string RouteDetailspageViewModel_RestartRoute {
            get {
                return ResourceManager.GetString("RouteDetailspageViewModel_RestartRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Route wurde bereits begonnen:.
        /// </summary>
        public static string RouteDetailspageViewModel_RouteStarted {
            get {
                return ResourceManager.GetString("RouteDetailspageViewModel_RouteStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Kilometer.
        /// </summary>
        public static string RoutesOverviewListItemViewModel_Distance {
            get {
                return ResourceManager.GetString("RoutesOverviewListItemViewModel_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Minuten.
        /// </summary>
        public static string RoutesOverviewListItemViewModel_Duration {
            get {
                return ResourceManager.GetString("RoutesOverviewListItemViewModel_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf der Route:.
        /// </summary>
        public static string RoutesOverviewView_Tags {
            get {
                return ResourceManager.GetString("RoutesOverviewView_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Einführung.
        /// </summary>
        public static string SettingsScreenView_AppIntro_Title {
            get {
                return ResourceManager.GetString("SettingsScreenView_AppIntro_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn diese Einstellung aktiviert ist, wird Audio automatisch für die aktuelle Seite gestartet..
        /// </summary>
        public static string SettingsScreenView_AutoStartAudio_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_AutoStartAudio_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch Audio beginnen.
        /// </summary>
        public static string SettingsScreenView_AutoStartAudio_Title {
            get {
                return ResourceManager.GetString("SettingsScreenView_AutoStartAudio_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn diese Einstellung aktiviert ist, wird nach Ende der Audiowiedergabe automatisch zur nächsten Seite gewechselt..
        /// </summary>
        public static string SettingsScreenView_AutoSwitchPage_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_AutoSwitchPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch Seiten wechseln.
        /// </summary>
        public static string SettingsScreenView_AutoSwitchPage_Title {
            get {
                return ResourceManager.GetString("SettingsScreenView_AutoSwitchPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sehenswürdigkeiten.
        /// </summary>
        public static string SettingsScreenView_POI_Title {
            get {
                return ResourceManager.GetString("SettingsScreenView_POI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn aktiviert, wird der Hinweis zur Audiowiedergabe erneut angezeigt.
        /// </summary>
        public static string SettingsScreenView_RepeatHintAudio_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_RepeatHintAudio_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn aktiviert, wird der Hinweis zum automatischen Seitenwechsel erneut angezeigt.
        /// </summary>
        public static string SettingsScreenView_RepeatHintAutoPageSwitch_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_RepeatHintAutoPageSwitch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn aktiviert, wird der Hinweis zur Zeitleiste erneut angezeigt.
        /// </summary>
        public static string SettingsScreenView_RepeatHintTimeSlider_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_RepeatHintTimeSlider_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn aktiviert, wird die App Einführung beim nächsten Start erneut angezeigt.
        /// </summary>
        public static string SettingsScreenView_RepeatIntro_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_RepeatIntro_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erlebe und entdecke selbst mit dem Smartphone Geschichte und Kultur vor Ort.
        /// </summary>
        public static string UserOnboarding_Explore_Text {
            get {
                return ResourceManager.GetString("UserOnboarding_Explore_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paderborn erkunden.
        /// </summary>
        public static string UserOnboarding_Explore_Title {
            get {
                return ResourceManager.GetString("UserOnboarding_Explore_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEITER.
        /// </summary>
        public static string UserOnboarding_Forward {
            get {
                return ResourceManager.GetString("UserOnboarding_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLES KLAR.
        /// </summary>
        public static string UserOnboarding_Ok {
            get {
                return ResourceManager.GetString("UserOnboarding_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkunde frei oder anhand themenspezifischer Routen Paderborn.
        /// </summary>
        public static string UserOnboarding_Route_Text {
            get {
                return ResourceManager.GetString("UserOnboarding_Route_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themenspezifische Routen.
        /// </summary>
        public static string UserOnboarding_Route_Title {
            get {
                return ResourceManager.GetString("UserOnboarding_Route_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÜBERSPRINGEN.
        /// </summary>
        public static string UserOnboarding_Skip {
            get {
                return ResourceManager.GetString("UserOnboarding_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine sich weiterentwickelnde App erstellt von Studierenden der Universität Paderborn.
        /// </summary>
        public static string UserOnboarding_Students_Text {
            get {
                return ResourceManager.GetString("UserOnboarding_Students_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Von Studierenden.
        /// </summary>
        public static string UserOnboarding_Students_Title {
            get {
                return ResourceManager.GetString("UserOnboarding_Students_Title", resourceCulture);
            }
        }
    }
}
