// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PaderbornUniversity.SILab.Hip.Mobile.UI.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PaderbornUniversity.SILab.Hip.Mobile.UI.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string LicenseScreenView_Agreement_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Agreement_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Agreement_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Agreement_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Contribution_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Contribution_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Copyright_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Copyright_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Copyright_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Copyright_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_CreditsImagesAutocarousel_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_CreditsImagesAutocarousel_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_CreditsImagesAutocarousel_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_CreditsImagesAutocarousel_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_CSL_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_CSL_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_CSL_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_CSL_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_DatabaseData_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_DatabaseData_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_DatabaseData_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_DatabaseData_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_FeedbackData_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_FeedbackData_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_FeedbackData_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_FeedbackData_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Fody_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Fody_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Fody_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Fody_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_FurtherInfo_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_FurtherInfo_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_FurtherInfo_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_FurtherInfo_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_HockeyApp_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_HockeyApp_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_HockeyApp_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_HockeyApp_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Impressum_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Impressum_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Impressum_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Impressum_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Itinero_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Itinero_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Itinero_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Itinero_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Liability_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Liability_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Liability_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Liability_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_License_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_License_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_MapIcons_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_MapIcons_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_MapIcons_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_MapIcons_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_MaterialIcons_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_MaterialIcons_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_MaterialIcons_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_MaterialIcons_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_OSMBonusPack_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_OSMBonusPack_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_OSMBonusPack_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_OSMBonusPack_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Osmdroid_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Osmdroid_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Osmdroid_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Osmdroid_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_OsmSharp_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_OsmSharp_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_OsmSharp_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_OsmSharp_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_PrivacyPolicy_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_PrivacyPolicy_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_PrivacyPolicy_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_PrivacyPolicy_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Realm_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Realm_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Realm_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Realm_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Reminiscence_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Reminiscence_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Reminiscence_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Reminiscence_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_RightOfPP_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_RightOfPP_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_RightOfPP_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_RightOfPP_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_SettingsPlugin_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_SettingsPlugin_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_SettingsPlugin_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_SettingsPlugin_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_ToU_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_ToU_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_ToU_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_ToU_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Transparancy_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Transparancy_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Transparancy_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Transparancy_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Unity_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_Unity_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_Unity_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_Unity_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_UsagePersonalData_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_UsagePersonalData_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_UsagePersonalData_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_UsagePersonalData_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_XSL_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_XSL_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_XSL_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_XSL_Title", resourceCulture);
            }
        }
        
        public static string MainPageViewModel_Feedback {
            get {
                return ResourceManager.GetString("MainPageViewModel_Feedback", resourceCulture);
            }
        }
        
        public static string MainPageViewModel_LegalNotices {
            get {
                return ResourceManager.GetString("MainPageViewModel_LegalNotices", resourceCulture);
            }
        }
        
        public static string MainPageViewModel_OverviewPage {
            get {
                return ResourceManager.GetString("MainPageViewModel_OverviewPage", resourceCulture);
            }
        }
        
        public static string MainPageViewModel_Routes {
            get {
                return ResourceManager.GetString("MainPageViewModel_Routes", resourceCulture);
            }
        }
        
        public static string MainPageViewModel_Settings {
            get {
                return ResourceManager.GetString("MainPageViewModel_Settings", resourceCulture);
            }
        }
        
        public static string MainPage_MenuTitle {
            get {
                return ResourceManager.GetString("MainPage_MenuTitle", resourceCulture);
            }
        }
        
        public static string RouteDetailsPageViewModel_Description {
            get {
                return ResourceManager.GetString("RouteDetailsPageViewModel_Description", resourceCulture);
            }
        }
        
        public static string RouteDetailsPageViewModel_Distance {
            get {
                return ResourceManager.GetString("RouteDetailsPageViewModel_Distance", resourceCulture);
            }
        }
        
        public static string RouteDetailsPageViewModel_Duration {
            get {
                return ResourceManager.GetString("RouteDetailsPageViewModel_Duration", resourceCulture);
            }
        }
        
        public static string RouteDetailsPageViewModel_Map {
            get {
                return ResourceManager.GetString("RouteDetailsPageViewModel_Map", resourceCulture);
            }
        }
        
        public static string RouteDetailsPage_PlayAudio {
            get {
                return ResourceManager.GetString("RouteDetailsPage_PlayAudio", resourceCulture);
            }
        }
        
        public static string RouteDetailsPage_PauseAudio {
            get {
                return ResourceManager.GetString("RouteDetailsPage_PauseAudio", resourceCulture);
            }
        }
        
        public static string RouteDetailsPage_StartRoute {
            get {
                return ResourceManager.GetString("RouteDetailsPage_StartRoute", resourceCulture);
            }
        }
        
        public static string RouteDetailsPage_Tags {
            get {
                return ResourceManager.GetString("RouteDetailsPage_Tags", resourceCulture);
            }
        }
        
        public static string RoutesOverviewListItemViewModel_Distance {
            get {
                return ResourceManager.GetString("RoutesOverviewListItemViewModel_Distance", resourceCulture);
            }
        }
        
        public static string RoutesOverviewListItemViewModel_Duration {
            get {
                return ResourceManager.GetString("RoutesOverviewListItemViewModel_Duration", resourceCulture);
            }
        }
        
        public static string RoutesOverviewView_Tags {
            get {
                return ResourceManager.GetString("RoutesOverviewView_Tags", resourceCulture);
            }
        }
        
        public static string AudioToolbarView_Caption {
            get {
                return ResourceManager.GetString("AudioToolbarView_Caption", resourceCulture);
            }
        }
        
        public static string AudioToolbarView_Pause {
            get {
                return ResourceManager.GetString("AudioToolbarView_Pause", resourceCulture);
            }
        }
        
        public static string AudioToolbarView_Play {
            get {
                return ResourceManager.GetString("AudioToolbarView_Play", resourceCulture);
            }
        }
        
        public static string AudioToolbarView_Progress {
            get {
                return ResourceManager.GetString("AudioToolbarView_Progress", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_AppIntro_Title {
            get {
                return ResourceManager.GetString("SettingsScreenView_AppIntro_Title", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_AutoStartAudio_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_AutoStartAudio_Text", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_AutoStartAudio_Title {
            get {
                return ResourceManager.GetString("SettingsScreenView_AutoStartAudio_Title", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_AutoSwitchPage_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_AutoSwitchPage_Text", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_AutoSwitchPage_Title {
            get {
                return ResourceManager.GetString("SettingsScreenView_AutoSwitchPage_Title", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_POI_Title {
            get {
                return ResourceManager.GetString("SettingsScreenView_POI_Title", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_RepeatHintAudio_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_RepeatHintAudio_Text", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_RepeatHintAutoPageSwitch_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_RepeatHintAutoPageSwitch_Text", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_RepeatHintTimeSlider_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_RepeatHintTimeSlider_Text", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_RepeatIntro_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_RepeatIntro_Text", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_DownloadData_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_DownloadData_Text", resourceCulture);
            }
        }
        
        public static string ExhibitDetailsPage_AudioToolbar {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_AudioToolbar", resourceCulture);
            }
        }
        
        public static string ExhibitDetailsPage_AgreeFeature {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_AgreeFeature", resourceCulture);
            }
        }
        
        public static string ExhibitDetailsPage_AudioPlay {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_AudioPlay", resourceCulture);
            }
        }
        
        public static string ExhibitDetailsPage_DisagreeFeature {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_DisagreeFeature", resourceCulture);
            }
        }
        
        public static string ExhibitDetailsPage_Hinweis {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_Hinweis", resourceCulture);
            }
        }
        
        public static string ExhibitDetailsPage_PageSwitch {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_PageSwitch", resourceCulture);
            }
        }
        
        public static string AudioTranscriptView_Sources_Title {
            get {
                return ResourceManager.GetString("AudioTranscriptView_Sources_Title", resourceCulture);
            }
        }
        
        public static string AudioTranscriptView_Subtitles_Title {
            get {
                return ResourceManager.GetString("AudioTranscriptView_Subtitles_Title", resourceCulture);
            }
        }
        
        public static string UserOnboarding_Explore_Text {
            get {
                return ResourceManager.GetString("UserOnboarding_Explore_Text", resourceCulture);
            }
        }
        
        public static string UserOnboarding_Explore_Title {
            get {
                return ResourceManager.GetString("UserOnboarding_Explore_Title", resourceCulture);
            }
        }
        
        public static string UserOnboarding_Forward {
            get {
                return ResourceManager.GetString("UserOnboarding_Forward", resourceCulture);
            }
        }
        
        public static string UserOnboarding_Ok {
            get {
                return ResourceManager.GetString("UserOnboarding_Ok", resourceCulture);
            }
        }
        
        public static string UserOnboarding_Route_Text {
            get {
                return ResourceManager.GetString("UserOnboarding_Route_Text", resourceCulture);
            }
        }
        
        public static string UserOnboarding_Route_Title {
            get {
                return ResourceManager.GetString("UserOnboarding_Route_Title", resourceCulture);
            }
        }
        
        public static string UserOnboarding_Skip {
            get {
                return ResourceManager.GetString("UserOnboarding_Skip", resourceCulture);
            }
        }
        
        public static string UserOnboarding_Students_Text {
            get {
                return ResourceManager.GetString("UserOnboarding_Students_Text", resourceCulture);
            }
        }
        
        public static string UserOnboarding_Students_Title {
            get {
                return ResourceManager.GetString("UserOnboarding_Students_Title", resourceCulture);
            }
        }
        
        public static string LoadingPage_Subtext {
            get {
                return ResourceManager.GetString("LoadingPage_Subtext", resourceCulture);
            }
        }
        
        public static string LoadingPage_Text {
            get {
                return ResourceManager.GetString("LoadingPage_Text", resourceCulture);
            }
        }
        
        public static string MapRenderer_NoLocation_Text {
            get {
                return ResourceManager.GetString("MapRenderer_NoLocation_Text", resourceCulture);
            }
        }
        
        public static string RouteDetailspageViewModel_Back {
            get {
                return ResourceManager.GetString("RouteDetailspageViewModel_Back", resourceCulture);
            }
        }
        
        public static string RouteDetailspageViewModel_ContinueRoute {
            get {
                return ResourceManager.GetString("RouteDetailspageViewModel_ContinueRoute", resourceCulture);
            }
        }
        
        public static string RouteDetailspageViewModel_RestartRoute {
            get {
                return ResourceManager.GetString("RouteDetailspageViewModel_RestartRoute", resourceCulture);
            }
        }
        
        public static string RouteDetailspageViewModel_RouteStarted {
            get {
                return ResourceManager.GetString("RouteDetailspageViewModel_RouteStarted", resourceCulture);
            }
        }
        
        public static string ExhibitDetailsPage_AdditionalInformation {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_AdditionalInformation", resourceCulture);
            }
        }
        
        public static string ExhibitOrRouteNearby_Confirm {
            get {
                return ResourceManager.GetString("ExhibitOrRouteNearby_Confirm", resourceCulture);
            }
        }
        
        public static string ExhibitNearby_ExhibitNearby {
            get {
                return ResourceManager.GetString("ExhibitNearby_ExhibitNearby", resourceCulture);
            }
        }
        
        public static string ExhibitOrRouteNearby_Question_Part1 {
            get {
                return ResourceManager.GetString("ExhibitOrRouteNearby_Question_Part1", resourceCulture);
            }
        }
        
        public static string ExhibitOrRouteNearby_Question_Part2 {
            get {
                return ResourceManager.GetString("ExhibitOrRouteNearby_Question_Part2", resourceCulture);
            }
        }
        
        public static string ExhibitOrRouteNearby_Reject {
            get {
                return ResourceManager.GetString("ExhibitOrRouteNearby_Reject", resourceCulture);
            }
        }
        
        public static string RouteNearby {
            get {
                return ResourceManager.GetString("RouteNearby", resourceCulture);
            }
        }
        
        public static string SkipExhibit_Confirm {
            get {
                return ResourceManager.GetString("SkipExhibit_Confirm", resourceCulture);
            }
        }
        
        public static string SkipExhibit_Question_Part1 {
            get {
                return ResourceManager.GetString("SkipExhibit_Question_Part1", resourceCulture);
            }
        }
        
        public static string SkipExhibit_Question_Part2 {
            get {
                return ResourceManager.GetString("SkipExhibit_Question_Part2", resourceCulture);
            }
        }
        
        public static string SkipExhibit_Reject {
            get {
                return ResourceManager.GetString("SkipExhibit_Reject", resourceCulture);
            }
        }
        
        public static string SkipExhibit_Title {
            get {
                return ResourceManager.GetString("SkipExhibit_Title", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_FurtherSettings_Title {
            get {
                return ResourceManager.GetString("SettingsScreenView_FurtherSettings_Title", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_RemoveAllDownloadsButton_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_RemoveAllDownloadsButton_Text", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_RemoveAllDownloadsPrompt_Confirm {
            get {
                return ResourceManager.GetString("SettingsScreenView_RemoveAllDownloadsPrompt_Confirm", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_RemoveAllDownloadsPrompt_Question {
            get {
                return ResourceManager.GetString("SettingsScreenView_RemoveAllDownloadsPrompt_Question", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_RemoveAllDownloadsPrompt_Reject {
            get {
                return ResourceManager.GetString("SettingsScreenView_RemoveAllDownloadsPrompt_Reject", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_RemoveAllDownloadsPrompt_Title {
            get {
                return ResourceManager.GetString("SettingsScreenView_RemoveAllDownloadsPrompt_Title", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_RemoveAllDownloads_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_RemoveAllDownloads_Text", resourceCulture);
            }
        }
        
        public static string ExhibitsOverviewView_EmptyList {
            get {
                return ResourceManager.GetString("ExhibitsOverviewView_EmptyList", resourceCulture);
            }
        }
        
        public static string RoutesOverviewView_EmptyList {
            get {
                return ResourceManager.GetString("RoutesOverviewView_EmptyList", resourceCulture);
            }
        }
        
        public static string DownloadData_Title {
            get {
                return ResourceManager.GetString("DownloadData_Title", resourceCulture);
            }
        }
        
        public static string DownloadData_Cancel {
            get {
                return ResourceManager.GetString("DownloadData_Cancel", resourceCulture);
            }
        }
        
        public static string DownloadData_Accept {
            get {
                return ResourceManager.GetString("DownloadData_Accept", resourceCulture);
            }
        }
        
        public static string DownloadData_Always {
            get {
                return ResourceManager.GetString("DownloadData_Always", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_Data_Title {
            get {
                return ResourceManager.GetString("SettingsScreenView_Data_Title", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_WifiOnly_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_WifiOnly_Text", resourceCulture);
            }
        }
        
        public static string LoadingPageViewModel_BaseData_DatabaseUpToDateCheckFailed {
            get {
                return ResourceManager.GetString("LoadingPageViewModel_BaseData_DatabaseUpToDateCheckFailed", resourceCulture);
            }
        }
        
        public static string LoadingPageViewModel_BaseData_DataAvailable {
            get {
                return ResourceManager.GetString("LoadingPageViewModel_BaseData_DataAvailable", resourceCulture);
            }
        }
        
        public static string LoadingPageViewModel_BaseData_DownloadViaMobile {
            get {
                return ResourceManager.GetString("LoadingPageViewModel_BaseData_DownloadViaMobile", resourceCulture);
            }
        }
        
        public static string LoadingPageViewModel_BaseData_MobileDownload_Cancel {
            get {
                return ResourceManager.GetString("LoadingPageViewModel_BaseData_MobileDownload_Cancel", resourceCulture);
            }
        }
        
        public static string LoadingPageViewModel_BaseData_MobileDownload_Confirm {
            get {
                return ResourceManager.GetString("LoadingPageViewModel_BaseData_MobileDownload_Confirm", resourceCulture);
            }
        }
        
        public static string LoadingPageViewModel_LoadingError_Confirm {
            get {
                return ResourceManager.GetString("LoadingPageViewModel_LoadingError_Confirm", resourceCulture);
            }
        }
        
        public static string StorageTitle {
            get {
                return ResourceManager.GetString("StorageTitle", resourceCulture);
            }
        }
        
        public static string DownloadDetails_Text_Part1 {
            get {
                return ResourceManager.GetString("DownloadDetails_Text_Part1", resourceCulture);
            }
        }
        
        public static string DownloadDetails_Text_Part2 {
            get {
                return ResourceManager.GetString("DownloadDetails_Text_Part2", resourceCulture);
            }
        }
        
        public static string MainPageViewModel_Account {
            get {
                return ResourceManager.GetString("MainPageViewModel_Account", resourceCulture);
            }
        }
        
        public static string MainPageViewModel_Profile {
            get {
                return ResourceManager.GetString("MainPageViewModel_Profile", resourceCulture);
            }
        }
        
        public static string ProfileView_Achievements {
            get {
                return ResourceManager.GetString("ProfileView_Achievements", resourceCulture);
            }
        }
        
        public static string ProfileView_Statistic {
            get {
                return ResourceManager.GetString("ProfileView_Statistic", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string ProfileView_Overview_Achievements {
            get {
                return ResourceManager.GetString("ProfileView_Overview_Achievements", resourceCulture);
            }
        }
        
        public static string ProfileView_Overview_Progress {
            get {
                return ResourceManager.GetString("ProfileView_Overview_Progress", resourceCulture);
            }
        }
        
        public static string ProfileView_Overview_Score {
            get {
                return ResourceManager.GetString("ProfileView_Overview_Score", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Error_Wrong_Credentials {
            get {
                return ResourceManager.GetString("LoginScreenView_Error_Wrong_Credentials", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Error_Unknown_Email {
            get {
                return ResourceManager.GetString("LoginScreenView_Error_Unknown_Email", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Error_Wrong_Password {
            get {
                return ResourceManager.GetString("LoginScreenView_Error_Wrong_Password", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Login {
            get {
                return ResourceManager.GetString("LoginScreenView_Login", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Password {
            get {
                return ResourceManager.GetString("LoginScreenView_Password", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Register {
            get {
                return ResourceManager.GetString("LoginScreenView_Register", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Email {
            get {
                return ResourceManager.GetString("LoginScreenView_Email", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Forgot_Password {
            get {
                return ResourceManager.GetString("LoginScreenView_Forgot_Password", resourceCulture);
            }
        }
        
        public static string LoadingPageViewModel_BaseData_DownloadFailed_Text {
            get {
                return ResourceManager.GetString("LoadingPageViewModel_BaseData_DownloadFailed_Text", resourceCulture);
            }
        }
        
        public static string LoadingPageViewModel_BaseData_DownloadFailed_Title {
            get {
                return ResourceManager.GetString("LoadingPageViewModel_BaseData_DownloadFailed_Title", resourceCulture);
            }
        }
        
        public static string LoadingPageViewModel_BaseData_OnlyMobile {
            get {
                return ResourceManager.GetString("LoadingPageViewModel_BaseData_OnlyMobile", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Email {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Email", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Forgot_Password {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Forgot_Password", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Info {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Info", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Invalid_Email {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Invalid_Email", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Reset_Password {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Reset_Password", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Unknown_Email {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Unknown_Email", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Email {
            get {
                return ResourceManager.GetString("RegisterScreenView_Email", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Password {
            get {
                return ResourceManager.GetString("RegisterScreenView_Password", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_RepeatPassword {
            get {
                return ResourceManager.GetString("RegisterScreenView_RepeatPassword", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Register {
            get {
                return ResourceManager.GetString("RegisterScreenView_Register", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Error_Register_Fail {
            get {
                return ResourceManager.GetString("RegisterScreenView_Error_Register_Fail", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Alert_Description {
            get {
                return ResourceManager.GetString("RegisterScreenView_Alert_Description", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Alert_Ok {
            get {
                return ResourceManager.GetString("RegisterScreenView_Alert_Ok", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Alert_Registered {
            get {
                return ResourceManager.GetString("RegisterScreenView_Alert_Registered", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Error_Empty_Email_And_Password {
            get {
                return ResourceManager.GetString("RegisterScreenView_Error_Empty_Email_And_Password", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Error_Empty_Password {
            get {
                return ResourceManager.GetString("RegisterScreenView_Error_Empty_Password", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Alert_Description {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Alert_Description", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Alert_Ok {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Alert_Ok", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Alert_Password_Resetted {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Alert_Password_Resetted", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Error_Empty_Email {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Error_Empty_Email", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Error_Empty_Email {
            get {
                return ResourceManager.GetString("LoginScreenView_Error_Empty_Email", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Error_Empty_Email_And_Password {
            get {
                return ResourceManager.GetString("LoginScreenView_Error_Empty_Email_And_Password", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Error_Empty_Password {
            get {
                return ResourceManager.GetString("LoginScreenView_Error_Empty_Password", resourceCulture);
            }
        }
        
        public static string LoginScreenView_Dialog_Login {
            get {
                return ResourceManager.GetString("LoginScreenView_Dialog_Login", resourceCulture);
            }
        }
        
        public static string Alert_No_Internet_Description {
            get {
                return ResourceManager.GetString("Alert_No_Internet_Description", resourceCulture);
            }
        }
        
        public static string Alert_No_Internet_Title {
            get {
                return ResourceManager.GetString("Alert_No_Internet_Title", resourceCulture);
            }
        }
        
        public static string Alert_Server_Error_Description {
            get {
                return ResourceManager.GetString("Alert_Server_Error_Description", resourceCulture);
            }
        }
        
        public static string Alert_Server_Error_Title {
            get {
                return ResourceManager.GetString("Alert_Server_Error_Title", resourceCulture);
            }
        }
        
        public static string Alert_Unknown_Error_Description {
            get {
                return ResourceManager.GetString("Alert_Unknown_Error_Description", resourceCulture);
            }
        }
        
        public static string Alert_Unknown_Error_Title {
            get {
                return ResourceManager.GetString("Alert_Unknown_Error_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenViewModel_UnlockExhibits_Confirm {
            get {
                return ResourceManager.GetString("LicenseScreenViewModel_UnlockExhibits_Confirm", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_User_Dialogs_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_User_Dialogs_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_User_Dialogs_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_User_Dialogs_Title", resourceCulture);
            }
        }
        
        public static string CharacterSelectionPage_Adventurer_Text {
            get {
                return ResourceManager.GetString("CharacterSelectionPage_Adventurer_Text", resourceCulture);
            }
        }
        
        public static string CharacterSelectionPage_Professor_Text {
            get {
                return ResourceManager.GetString("CharacterSelectionPage_Professor_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_CreditsImagesCharacterSelection_Text {
            get {
                return ResourceManager.GetString("LicenseScreenView_CreditsImagesCharacterSelection_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenView_CreditsImagesCharacterSelection_Title {
            get {
                return ResourceManager.GetString("LicenseScreenView_CreditsImagesCharacterSelection_Title", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Error_Empty_Email {
            get {
                return ResourceManager.GetString("RegisterScreenView_Error_Empty_Email", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Error_Mismatch_Password {
            get {
                return ResourceManager.GetString("RegisterScreenView_Error_Mismatch_Password", resourceCulture);
            }
        }
        
        public static string RegisterScreenView_Error_Invalid_Email {
            get {
                return ResourceManager.GetString("RegisterScreenView_Error_Invalid_Email", resourceCulture);
            }
        }
        
        public static string ExhibitDetailsPage_Distance_alert_confirm {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_Distance_alert_confirm", resourceCulture);
            }
        }
        
        public static string ExhibitDetailsPage_Distance_Text {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_Distance_Text", resourceCulture);
            }
        }
        
        public static string ExhibitDetailsPage_Distance_Title {
            get {
                return ResourceManager.GetString("ExhibitDetailsPage_Distance_Title", resourceCulture);
            }
        }
        
        public static string LicenseScreenViewModel_UnlockExhibits_Text {
            get {
                return ResourceManager.GetString("LicenseScreenViewModel_UnlockExhibits_Text", resourceCulture);
            }
        }
        
        public static string LicenseScreenViewModel_UnlockExhibits_Title {
            get {
                return ResourceManager.GetString("LicenseScreenViewModel_UnlockExhibits_Title", resourceCulture);
            }
        }
        
        public static string MainPageViewModel_Leaderboard {
            get {
                return ResourceManager.GetString("MainPageViewModel_Leaderboard", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_CharacterSelection_Text_IsAdventurer {
            get {
                return ResourceManager.GetString("SettingsScreenView_CharacterSelection_Text_IsAdventurer", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_CharacterSelection_Text_IsProfessor {
            get {
                return ResourceManager.GetString("SettingsScreenView_CharacterSelection_Text_IsProfessor", resourceCulture);
            }
        }
        
        public static string SettingsScreenView_CharacterSelection_Button_Text {
            get {
                return ResourceManager.GetString("SettingsScreenView_CharacterSelection_Button_Text", resourceCulture);
            }
        }
        
        public static string ProfileView_Adventurer {
            get {
                return ResourceManager.GetString("ProfileView_Adventurer", resourceCulture);
            }
        }
        
        public static string ProfileView_Button_Change_App_Mode {
            get {
                return ResourceManager.GetString("ProfileView_Button_Change_App_Mode", resourceCulture);
            }
        }
        
        public static string ProfileView_Professor {
            get {
                return ResourceManager.GetString("ProfileView_Professor", resourceCulture);
            }
        }
        
        public static string ExhibitRouteDownloadPageViewModel_Wifi_Only_Cancel {
            get {
                return ResourceManager.GetString("ExhibitRouteDownloadPageViewModel_Wifi_Only_Cancel", resourceCulture);
            }
        }
        
        public static string ExhibitRouteDownloadPageViewModel_Wifi_Only_Message {
            get {
                return ResourceManager.GetString("ExhibitRouteDownloadPageViewModel_Wifi_Only_Message", resourceCulture);
            }
        }
        
        public static string ExhibitRouteDownloadPageViewModel_Wifi_Only_Ok {
            get {
                return ResourceManager.GetString("ExhibitRouteDownloadPageViewModel_Wifi_Only_Ok", resourceCulture);
            }
        }
        
        public static string ExhibitRouteDownloadPageViewModel_Wifi_Only_Title {
            get {
                return ResourceManager.GetString("ExhibitRouteDownloadPageViewModel_Wifi_Only_Title", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Alert_No_Connection_Description {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Alert_No_Connection_Description", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Alert_No_Connection_Title {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Alert_No_Connection_Title", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Alert_Unknown_Error_Description {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Alert_Unknown_Error_Description", resourceCulture);
            }
        }
        
        public static string ForgotPasswordScreenView_Alert_Unknown_Error_Title {
            get {
                return ResourceManager.GetString("ForgotPasswordScreenView_Alert_Unknown_Error_Title", resourceCulture);
            }
        }
        
        public static string AchievementsScreenView_Score {
            get {
                return ResourceManager.GetString("AchievementsScreenView_Score", resourceCulture);
            }
        }
        
        public static string MainPageViewModel_Achievements {
            get {
                return ResourceManager.GetString("MainPageViewModel_Achievements", resourceCulture);
            }
        }
    }
}
