// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MaterialControlsSample
{
	public partial class MDButton : UIButton
	{
		public MDButton (IntPtr handle) : base (handle)
		{
		}
	}
}
